graph TD

Bid(楼号)---Dom
Rid(寝室号)---Dom
Flr(楼层)---Dom
Occ(住宿人数)---Dom

Dom[寝室]--1---Liv{居住}--n----Stu[学生]---Sid(学号)
Stu---Sna(姓名)
Stu---Sex(性别)

Liv---BId(床号)
Liv---IsL(是否寝室长)



Apf---SSt(存放状态)
Apf---DeT(存放时间)
Apf---PcT(取物时间)
Apf---Loc(存放位置)
Stu--1----Apf{存储}--n----Str[物品]
Str---INa(物品名称)
Str---Ity(物品类型)

Stu[学生]--1----Sub{提交}

Sub---RTm(时间)

Sub--n----Rep[报修单]
Dom--1----Abt{关联}--n----Rep

Rep---RId(单号)
Rep---RTy(类型)
Rep---RCo(内容)
Rep---RPr(人员)
Rep---RFe(费用)
Rep---RSt(状态)

Stu--1----App{访问}--n----SIO[访员人次]
Dom[寝室]--1---App
App---VTm(访问时间)
App---VTy(访问类型)
App---VPu(访问目的)
SIO---VNa(姓名)
SIO---Phc(手机号)

Dom[寝室]--1---Has{产生/支付}--n----Utl[水电]---Uid(单号)

Utl---Wc(水费)
Utl---Ec(电费)
Utl---Sta(支付状态)
Has---Tim(支付时间)
Has---Mon(月份)

Dom[寝室]--1---Has2{产生}--n----Hev[卫生评比]---Eid(评比号)
Has2---Etm(时间)
Hev---Esc(分数)