### 5.31 隐身妙脆角
凉趁虹夏睡觉把她头上的妙脆角摘下来玩，结果手滑让它掉进一大包妙脆角里了。这些妙脆角长的太像了导致凉没法直接从里面把虹夏的那个挑出来。为了不被惩罚，凉只能趁虹夏醒来之前想办法把虹夏的妙脆角找出来。

凉把这包妙脆角铺在一个 $n\times m$ 网格上，每个妙脆角视为两直角边长为 $1$ 的直角三角形，所以两个妙脆角恰好能填满一个格子。她不知道虹夏的妙脆角是哪一个，于是她做以下两种操作的一种，两种操作每次均花费 $1$ 秒时间：
- 吃掉与一个妙脆角相连的所有脆角（如果两个妙脆角共享一条边，那么它们相连，此关系可传递），如果吃到了虹夏的妙脆角，凉可以立即发现。
- 选择一个只包含一个妙脆角的格子，压碎上面的妙脆角。如果那不是虹夏的妙脆角，那么这个格子将被一块方形妙脆角填满，否则凉可以立即发现。
凉想知道她最慢多久能找到虹夏的妙脆角。

第一行给出 $n,m$ 。
接下来 $n$ 行，每行 $4m$ 个数：$l_i,r_i,u_i,d_i$ ，分别代表当前格的左右上下四条边是否与格子中的妙脆角紧贴。

### 5.31 东尼意思
著名建筑师安东尼每天要解决尖塔中大量的多样性、公平性和包容性问题，如果不处理这些问题他就没法好好打牌了。

尖塔的一幕的地图是一张有 $n$ 个节点 $m$ 条单向边的图，从唯一的一个先古之民房间（记作 $1$ 号房间）出发，沿着任何一条路线向上行进，最终一定会到达唯一的一个 Boss 房间（记作 $n$ 号房间）。安东尼需要按顺序处理 $q$ 个问题：
* 多样性：给定一个房间编号 $x$，这个房间。
* 公平性：给定一个房间编号 $x$，要求三个数组在此位置的值递增。
* 包容性：给定 $id$ 和一个值 $x$，要求此数组的所有值总和不能超过 $x$ 。
### 6.1 锉冰
来自台北的张姐正在狂炫锉冰。
```mermaid
graph TD

Bid(楼号)---Dom
Rid(寝室号)---Dom
Flr(楼层)---Dom
Occ(住宿人数)---Dom

Dom[寝室]--1---Liv{居住}--n----Stu[学生]---Sid(学号)
Stu[学生]---Sna(姓名)
Stu---Sex(性别)

Liv---BId(床号)
Liv---IsL(是否寝室长)

Apf---SSt(存放状态)
Apf---DeT(存放时间)
Apf---PcT(取物时间)
Apf---Loc(存放位置)
Stu--1----Apf{存储}--n----Str[物品]
Str---INa(物品名称)
Str---Ity(物品类型)

Dom--1----Sub{提交}

Sub---RTm(时间)

Sub--n----Rep[报修单]

Rep---RId(单号)
Rep---RTy(类型)
Rep---RCo(内容)
Rep---RPr(人员)
Rep---RFe(费用)
Rep---RSt(状态)

App{访问}--n----SIO[访员人次]
Dom[寝室]--1---App
App---VTm(访问时间)
App---VTy(访问类型)
App---VPu(访问目的)
SIO---VNa(姓名)
SIO---Phc(手机号)

Dom[寝室]--1---Has{产生/支付}--n----Utl[水电]---Uid(单号)

Utl---Wc(水电费)
Utl---Sta(支付状态)
Has---Tim(支付时间)
Has---Mon(月份)

Dom[寝室]--1---Has2{产生}--n----Hev[卫生评比]---Eid(评比号)
Has2---Etm(时间)
Hev---Esc(分数)
```