graph TD
Sid(学号)---Stu
Sna(姓名)---Stu[学生]
Sex(性别)---Stu

Stu--1---App{访问}--n----SIO[访员人次]

Bid(楼号)---Dom
Rid(寝室号)---Dom
Flr(楼层)---Dom
Occ(住宿人数)---Dom
Dom[寝室]--1---App
App---VTm(访问时间)
App---VTy(访问类型)
App---VPu(访问目的)
SIO---VNa(姓名)
SIO---Ity(手机号)