graph TD
Sna(姓名)---Stu
Sex(性别)---Stu

Sid(学号)---Stu[学生]--1---Sub{提交}

Sub---RTm(时间)

Sub--n----Rep[报修单]
Dom--1---Abt{关联}--n----Rep

Rep---RId(单号)
Rep---RTy(类型)
Rep---RCo(内容)
Rep---RPr(人员)
Rep---RFe(费用)
Rep---RSt(状态)

Dom[寝室]--1---Has{产生/支付}--n----Utl[水电]---Uid(单号)

Bid(楼号)---Dom
Rid(寝室号)---Dom
Flr(楼层)---Dom
Occ(住宿人数)---Dom

Utl---Wc(水费)
Utl---Ec(电费)
Utl---Sta(支付状态)
Has---Tim(支付时间)
Has---Mon(月份)

Dom[寝室]--1---Has2{产生}--n----Hev[卫生评比]---Eid(评比号)
Has2---Etm(时间)
Hev---Esc(分数)